# -*- coding: utf-8 -*-
"""S10_displays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MtijpxweG3kCwLqh8hIDtz400Ab6hpGf
"""

import matplotlib.pyplot as plt
class customPlots():

    def __init__(self,train_losses,train_acc, test_losses,test_acc):
      self.train_losses,self.train_acc=train_losses,train_acc
      self.test_losses,self.test_acc=test_losses,test_acc
     
    def plot_losses(self):
      fig, axs = plt.subplots(2,2,figsize=(15,10))
      axs[0, 0].plot(self.train_losses)
      axs[0, 0].set_title("Training Loss")
      axs[1,0].axis(ymin=50,ymax=100)
      axs[1, 0].plot(self.train_acc)
      axs[1, 0].set_title("Training Accuracy")
      axs[0, 1].plot(self.test_losses)
      axs[0, 1].set_title("Test Loss")
      axs[1,1].axis(ymin=50,ymax=100)
      axs[1, 1].plot(self.test_acc)
      axs[1, 1].set_title("Test Accuracy")